version: '3'
services:
  maven-jdk9:
    build:
      context: maven
      dockerfile: jdk9/Dockerfile
    image: modlost/java-builder:1.0.0-maven-jdk9
  maven-jdk8:
    build:
      context: maven
      dockerfile: jdk8/Dockerfile
    image: modlost/java-builder:1.0.1-maven-jdk8
  maven-jdk7:
    build:
      context: maven
      dockerfile: jdk7/Dockerfile
    image: modlost/java-builder:1.0.0-maven-jdk7
  maven-jdk6:
    build:
      context: maven
      dockerfile: jdk6/Dockerfile
    image: modlost/java-builder:1.0.0-maven-jdk6
#  gradle-jdk8:
#    build:
#      context: gradle
#      dockerfile: jdk8/Dockerfile
#    image: modlost/java-builder:gradle-jdk8
